import type { Metadata } from "next";
import { Inter, Wavefont, Linefont } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const wavefont = Wavefont({
  variable: "--font-wavefont",
  axes: ["ROND", "YELA"],
  display: "block",
});
const linefont = Linefont({
  variable: "--font-linefont",
  axes: ["wdth"],
  display: "block",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${wavefont.variable} ${linefont.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
